return {
    installKey = "id",
    rows = {
        {
            id = 990101,
            mainType = 1,
            showType = 1,
            name = "MOD 行动链演示",
            subheading = "先修复，再点射",
            desc = "一个使用两回合循环行动链的敌人正在等待挑战。",
            summary = "挑战两回合循环的行动链 Enemy。",
            replaceNode = {},
            finishReplaceNode = {},
            failReplaceNode = {},
            finish = 0,
            finishReward = { 0 },
            battleReward = { 100001 },
            winCondition = {},
            conditionRewards = {},
            robot = 11999,
            robotChips = {},
            gridPoolList = { 200 },
            robotGridPoolList = {},
            robotInitGrid = {},
            playerInitGrid = {},
            battleExtend = {},
            heroList = {},
            shopId = 0,
            optionType = 1,
            optionStatic = { 0 },
            optionRandom1 = {
                { id = 10051, weight = 100 },
            },
            optionRandom2 = {},
            optionRandom3 = {},
            heroIds = {},
            enemyHeroIds = {},
            dialogueId = 0,
            conditionGroup = 99,
            skybox = "Nebula_Coral_4K_3",
            dontShowEnemyEntrance = 0,
            useRetreat = 0,
            endTimeline = "",
            showLink = 0,
        },
    },
}
